--SELECT * FROM DBA_TABLESPACES;

--TASK 1
SELECT tablespace_name, contents, logging FROM dba_tablespaces;

--TASK 2
SELECT file_name, tablespace_name 
FROM dba_data_files 
UNION ALL 
SELECT file_name, tablespace_name 
FROM dba_temp_files;

--TASK 3
SELECT GROUP# FROM V$LOGFILE;
SELECT GROUP#, STATUS, MEMBERS FROM V$LOG;

--TASK 4
SELECT * FROM V$LOGFILE;

--TASK 5
SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;
ALTER SYSTEM SWITCH LOGFILE;

--TASK 6
ALTER DATABASE ADD LOGFILE GROUP 4 ('C:\APP\LENOVO\PRODUCT\21C\ORADATA\XE\REDO04a.LOG',
                                    'C:\APP\LENOVO\PRODUCT\21C\ORADATA\XE\REDO04b.LOG', 
                                    'C:\APP\LENOVO\PRODUCT\21C\ORADATA\XE\REDO04c.LOG')
SIZE 50M BLOCKSIZE 512;

--TASK 7
ALTER DATABASE DROP LOGFILE MEMBER 'C:\APP\LENOVO\PRODUCT\21C\ORADATA\XE\REDO04a.LOG';
ALTER DATABASE DROP LOGFILE MEMBER 'C:\APP\LENOVO\PRODUCT\21C\ORADATA\XE\REDO04b.LOG';
ALTER DATABASE DROP LOGFILE GROUP 4;
ALTER DATABASE DROP LOGFILE MEMBER 'C:\APP\LENOVO\PRODUCT\21C\ORADATA\XE\REDO04c.LOG';

--TASK 8
SELECT NAME, LOG_MODE FROM V$DATABASE;

--TASK 9
SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;
SELECT * FROM V$LOG;
SELECT * FROM V$ARCHIVED_LOG;


--TASK 11
ALTER SYSTEM ARCHIVE LOG CURRENT;
SELECT sequence#, name
FROM v$archived_log
ORDER BY sequence# DESC;

--TASK 13
SELECT name FROM v$controlfile;

--TASK 14
SHOW PARAMETER CONTROL;

SELECT MAX(sequence#) FROM v$archived_log;
SELECT NAME FROM V$ARCHIVED_LOG;



--------
ALTER DATABASE BACKUP CONTROLFILE TO TRACE;
SELECT tablespace_name FROM dba_tablespaces WHERE contents = 'UNDO';
SELECT MAX(sequence#) FROM v$archived_log;
SELECT NAME FROM V$ARCHIVED_LOG;
SELECT NAME FROM V$CONTROLFILE;
SELECT GROUP# FROM V$LOG WHERE STATUS='CURRENT';
SHOW PARAMETER PFILE;
CREATE PFILE = 'p1.ora' FROM SPFILE;