ALTER SESSION SET "_oracle_script" = TRUE; 


--TASK 1
CREATE SMALLFILE TABLESPACE "TS_INS"
DATAFILE 'ts_ins.dbf'
SIZE 7M 
AUTOEXTEND ON NEXT 5M 
MAXSIZE 200M;

--TASK 2
CREATE TEMPORARY TABLESPACE "TS_INS_TEMP"
TEMPFILE 'ts_ins_temp.dbf'
SIZE 5M 
AUTOEXTEND ON NEXT 3M 
MAXSIZE 20M;

--TASK 3
select TABLESPACE_NAME from dba_tablespaces;

--TASK 4
select file_name, tablespace_name FROM DBA_DATA_FILES;

--TASK 5
CREATE ROLE RL_INSCORE;
GRANT CONNECT,
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    ALTER ANY TABLE,
    ALTER ANY PROCEDURE,
    DROP ANY TABLE,
    DROP ANY VIEW,
    DROP ANY PROCEDURE TO RL_INSCORE;
    
--TASK 6
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_INSCORE';

--TASK 7
SELECT * FROM USER_SYS_PRIVS; 
SELECT * FROM USER_TAB_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;

--TASK 8
CREATE PROFILE PF_INSCORE LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30

--TASK 9
SELECT * FROM DBA_PROFILES;

--TASK 10
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_INSCORE';

--TASK 11
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

--TASK 12
CREATE USER INSCORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_INS QUOTA UNLIMITED ON TS_INS
TEMPORARY TABLESPACE TS_INS_TEMP
PROFILE PF_INSCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE

GRANT RL_INSCORE TO INSCORE;

--TASK 13
--connect INSCORE/12345@//localhost:1522/xe

--TASK 16
ALTER USER INSCORE QUOTA 2M ON TS_INS;

--TASK 18
ALTER TABLESPACE TS_INS OFFLINE NORMAL;

--TASK 20
ALTER TABLESPACE TS_INS ONLINE;