 ALTER SESSION SET "_oracle_script" = TRUE;

DROP TABLESPACE TS_INS;
CREATE TABLESPACE TS_INS
    DATAFILE 'C:\TS_INS.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;

SELECT TABLESPACE_NAME, STATUS, contents logging from SYS.DBA_TABLESPACES
